services:
  photo-rust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photo-rust-service
    ports:
      - "8081:8081"
    environment:
      - RUST_PORT=8081
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - PORT=8081
    volumes:
      # Mount for temporary files
      - ./tmp:/app/tmp
      # Mount for logs
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - photo-network

networks:
  photo-network:
    driver: bridge 